# Generated by Django 2.2.16 on 2022-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220303_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите сюда текст комментария', verbose_name='Комментарий'),
        ),
    ]
